'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowUpRight, ArrowRight, Plus, CalendarDays, ChevronLeft, ChevronRight, Mail, Users, CheckCircle2, Clock3, Search, SlidersHorizontal, FileText, Send, Plug, CircleAlert, RefreshCw, Download, PanelsTopLeft, Sparkles, MessageSquare, Radio } from 'lucide-react'
import { CHANNELS, type ContentItem, type Channel, type Section } from '@/lib/platform/types'
import { usePlatform } from './provider'
import { InboxPage } from './inbox'

export function ChannelBadges({ channels }: { channels: Channel[] }) { return <span className="sg-channel-stack">{channels.map(c => <span key={c} title={CHANNELS[c].label} className="sg-channel-badge" style={{ background: CHANNELS[c].color }}>{CHANNELS[c].short}</span>)}</span> }
export function Status({ status }: { status: string }) { const labels: Record<string, string> = { review: 'Needs review', not_subscribed: 'Not subscribed' }; return <span className={`sg-status sg-status-${status}`}><span />{labels[status] ?? status.replaceAll('_', ' ')}</span> }
export function Empty({ title, detail, action }: { title: string; detail: string; action?: React.ReactNode }) { return <div className="sg-empty"><span className="sg-empty-icon"><Radio size={27} strokeWidth={1.5} /></span><h3>{title}</h3><p>{detail}</p>{action}</div> }
function Header({ title, description, children }: { title: string; description: string; children?: React.ReactNode }) { return <div className="sg-page-heading"><div><h1>{title}</h1><p>{description}</p></div><div className="sg-row">{children}</div></div> }
function DateLabel({ value }: { value: string | null }) { return <span>{value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : 'No date'}{value && <small>{new Date(value).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</small>}</span> }
export function WorkspacePage({ section }: { section: Section }) {
  const p = usePlatform()
  if (p.loading) return <div className="sg-loading" role="status"><RefreshCw size={22} className="sg-spin" /><h2>Opening your workspace…</h2></div>
  if (p.error && section !== 'inbox' && section !== 'connections') return <><Header title="Your new workspace" description="Email, social, and every conversation in one place." /><div className="sg-error-state"><CircleAlert size={25} /><h2>Workspace setup needs attention</h2><p>{p.error}</p><div className="sg-row"><button className="sg-button" onClick={() => void p.refresh()}><RefreshCw size={16} />Try again</button><Link className="sg-button sg-primary" href="/outreach">Open cold outreach</Link><Link className="sg-button" href="/preview/today">Explore the preview</Link></div></div></>
  switch (section) {
    case 'today': return <Overview />
    case 'inbox': return <InboxPage />
    case 'contacts': return <Contacts />
    case 'email': return <ContentLibrary email />
    case 'social': return <ContentLibrary />
    case 'calendar': return <Calendar />
    case 'reports': return <Reports />
    case 'connections': return <Connections />
  }
}
function Overview() {
  const { data, companyName, href, setEditor } = usePlatform()
  const review = data.content.filter(c => c.status === 'review')
  const planned = data.content.filter(c => c.status === 'planned').sort((a, b) => (a.planned_at ?? '').localeCompare(b.planned_at ?? ''))
  const live = data.accounts.filter(a => a.status === 'connected')
  return <>
    <Header title="Make room for good conversations." description={`${companyName}’s email and social, brought together.`}><Link className="sg-button" href={href('/calendar')}><CalendarDays size={16} />View calendar</Link></Header>
    <div className="sg-overview-grid"><section className="sg-focus-panel"><div className="sg-focus-copy"><span className="sg-focus-tag"><span />Your workspace, in focus</span><h2>A clear view.<br />A thoughtful next move.</h2><p>Bring your next campaign to life, keep the conversation going, and give every channel a little more intention.</p><button className="sg-button sg-white" onClick={() => setEditor({ kind: 'content', channel: 'linkedin' })}>Create something <Plus size={16} /></button></div><div className="sg-orbit" aria-hidden="true"><div className="sg-orbit-ring" /><div className="sg-orbit-ring sg-orbit-ring-inner" /><span className="sg-orbit-center"><Radio size={38} /></span><span className="sg-orbit-icon sg-orbit-mail"><Mail size={24} /></span><span className="sg-orbit-icon sg-orbit-social"><MessageSquare size={23} /></span><span className="sg-orbit-icon sg-orbit-calendar"><CalendarDays size={22} /></span><span className="sg-orbit-dot" /></div></section>
      <section className="sg-attention"><div className="sg-section-title"><h2>Your next moves</h2><span className="sg-muted">{review.length + data.outreach.failed} to review</span></div><Link href={href('/social')} className="sg-attention-row"><span className="sg-soft-icon sg-orange"><FileText size={19} /></span><div><strong>{review.length ? `${review.length} draft${review.length > 1 ? 's' : ''} ready for review` : 'Shape your next story'}</strong><small>{review.length ? 'Give your content a final look' : 'Start with a social or email draft'}</small></div><ArrowUpRight size={17} /></Link><Link href="/outreach/schedule" className="sg-attention-row"><span className="sg-soft-icon sg-blue"><Send size={18} /></span><div><strong>{data.outreach.queued} outreach emails queued</strong><small>{data.outreach.failed ? `${data.outreach.failed} sends need attention` : 'Review your sending schedule'}</small></div><ArrowUpRight size={17} /></Link><Link href={href('/connections')} className="sg-attention-row"><span className="sg-soft-icon sg-green"><Plug size={19} /></span><div><strong>{live.length} connected accounts</strong><small>Review channel access and setup</small></div><ArrowUpRight size={17} /></Link></section></div>
    <div className="sg-stat-strip">{[{ label: 'Content in progress', value: data.content.filter(c => c.status !== 'archived').length, sub: 'Across email and social', icon: PanelsTopLeft }, { label: 'Planned content', value: planned.length, sub: 'On your content calendar', icon: CalendarDays }, { label: 'Contacts', value: data.contacts.length, sub: `${data.contacts.filter(c => c.subscription === 'subscribed').length} email subscribers`, icon: Users }, { label: 'Outreach emails sent', value: data.outreach.sent, sub: 'All-time recorded sends', icon: Send }].map(s => <div className="sg-stat" key={s.label}><div><span>{s.label}</span><s.icon size={17} /></div><strong>{s.value.toLocaleString()}</strong><small>{s.sub}</small></div>)}</div>
    <div className="sg-bottom-grid"><section className="sg-panel"><div className="sg-section-title"><div><h2>On the calendar</h2><p>A little planning goes a long way.</p></div><Link href={href('/calendar')} className="sg-text-link">View all <ArrowUpRight size={14} /></Link></div>{planned.length ? planned.slice(0, 4).map(item => <button key={item.id} className="sg-planned-row" onClick={() => setEditor({ kind: 'content', item })}><span className="sg-date-tile"><small>{new Date(item.planned_at!).toLocaleDateString(undefined, { month: 'short' })}</small><strong>{new Date(item.planned_at!).getDate()}</strong></span><div className="sg-grow"><strong>{item.title}</strong><small>{item.channels.map(c => CHANNELS[c].label).join(', ')}</small></div><ChannelBadges channels={item.channels} /><ChevronRight size={15} /></button>) : <Empty title="Your next story starts here" detail="Create a draft and give it a date to see it on your calendar." action={<button className="sg-button" onClick={() => setEditor({ kind: 'content' })}>Create a draft</button>} />}</section><section className="sg-panel"><div className="sg-section-title"><div><h2>Campaigns with a purpose</h2><p>Connect the pieces of your next big idea.</p></div><button className="sg-icon-button" aria-label="Create campaign" onClick={() => setEditor({ kind: 'campaign' })}><Plus size={18} /></button></div>{data.campaigns.length ? data.campaigns.slice(0, 3).map(c => <button className="sg-campaign-summary" key={c.id} onClick={() => setEditor({ kind: 'campaign', item: c })}><div className="sg-row sg-between"><span className="sg-campaign-symbol"><PanelsTopLeft size={19} /></span><Status status={c.status} /></div><h3>{c.name}</h3><p>{c.objective || 'Add an objective to guide your campaign.'}</p><div className="sg-row sg-between"><small>{data.content.filter(x => x.campaign_id === c.id).length} content pieces</small><ArrowUpRight size={17} /></div></button>) : <Empty title="Give your content a shared goal" detail="Group your email and social drafts in a campaign." action={<button className="sg-button" onClick={() => setEditor({ kind: 'campaign' })}>Create campaign</button>} />}</section></div>
  </>
}
function ContentLibrary({ email = false }: { email?: boolean }) {
  const { data, setEditor, href } = usePlatform()
  const [filter, setFilter] = useState('all')
  const [query, setQuery] = useState('')
  const [channel, setChannel] = useState('all')
  const [campaign, setCampaign] = useState('all')
  const collection = data.content.filter(c => email ? c.channels.includes('email') : c.channels.some(x => x !== 'email'))
  const shown = collection.filter(c => (filter === 'all' ? c.status !== 'archived' : c.status === filter) && (channel === 'all' || c.channels.includes(channel as Channel)) && (campaign === 'all' || c.campaign_id === campaign) && `${c.title} ${c.body}`.toLowerCase().includes(query.toLowerCase()))
  return <><Header title={email ? 'Email, with a little more intention.' : 'Good ideas belong out in the world.'} description={email ? 'Plan newsletters and campaigns alongside your cold outreach.' : 'One place to draft, review, and plan your social content.'}><button className="sg-button" onClick={() => setEditor({ kind: 'campaign' })}><Plus size={16} />Campaign</button><button className="sg-button sg-primary" onClick={() => setEditor({ kind: 'content', channel: email ? 'email' : 'linkedin' })}><Plus size={16} />{email ? 'Create email' : 'Create post'}</button></Header>
    {email && <div className="sg-email-paths"><Link href="/outreach"><span className="sg-soft-icon sg-blue"><Send size={22} /></span><div><h3>Cold outreach</h3><p>Prospect, personalize, and follow up with your existing sending engine.</p></div><ArrowUpRight size={20} /></Link><Link href={href('/inbox')}><span className="sg-soft-icon sg-green"><Mail size={22} /></span><div><h3>Everyday email</h3><p>Read and reply to conversations in your connected Gmail accounts.</p></div><ArrowUpRight size={20} /></Link></div>}
    <div className="sg-tabs" role="tablist" aria-label="Content status">{['all', 'draft', 'review', 'approved', 'planned', 'archived'].map(f => <button role="tab" aria-selected={filter === f} key={f} className={filter === f ? 'active' : ''} onClick={() => setFilter(f)}>{f === 'all' ? 'All content' : f === 'review' ? 'Needs review' : f}<span>{collection.filter(c => f === 'all' ? c.status !== 'archived' : c.status === f).length}</span></button>)}</div>
    <div className="sg-toolbar"><label className="sg-search-field"><Search size={16} /><input aria-label="Search content" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search your content…" /></label><div className="sg-row">{!email && <select aria-label="Filter channel" value={channel} onChange={e => setChannel(e.target.value)}><option value="all">All channels</option>{Object.entries(CHANNELS).filter(([id]) => id !== 'email').map(([id, c]) => <option key={id} value={id}>{c.label}</option>)}</select>}<select aria-label="Filter campaign" value={campaign} onChange={e => setCampaign(e.target.value)}><option value="all">All campaigns</option>{data.campaigns.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div>
    <div className="sg-content-grid">{shown.map((item, index) => <button className="sg-content-card" key={item.id} onClick={() => setEditor({ kind: 'content', item })}><div className={`sg-content-art sg-art-${index % 4}`}><span>{item.channels.includes('email') ? <Mail size={35} strokeWidth={1.2} /> : <MessageSquare size={35} strokeWidth={1.2} />}</span><p>{item.title}</p><div className="sg-art-line" /></div><div className="sg-content-card-body"><div className="sg-row sg-between"><ChannelBadges channels={item.channels} /><Status status={item.status} /></div><h3>{item.title}</h3><p>{item.body || 'An idea waiting to take shape.'}</p><div className="sg-content-card-footer"><span><CalendarDays size={13} />{item.planned_at ? new Date(item.planned_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : 'Not planned'}</span><span>Edit draft <ArrowUpRight size={13} /></span></div></div></button>)}</div>
    {!shown.length && <Empty title={query || filter !== 'all' ? 'No content matches this view' : email ? 'Your next email starts here' : 'A fresh space for your ideas'} detail="Create a draft, choose your channels, and bring it onto the calendar." action={<button className="sg-button sg-primary" onClick={() => setEditor({ kind: 'content', channel: email ? 'email' : 'linkedin' })}><Plus size={16} />Create a draft</button>} />}
    <p className="sg-footer-note"><CircleAlert size={14} />{email ? 'Newsletter drafts are saved here. Bulk delivery is not enabled; cold outreach uses its existing sending controls.' : 'Planned posts are saved to your calendar. Automatic publishing is not enabled yet.'}</p>
  </>
}
function Contacts() {
  const { data, setEditor } = usePlatform()
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('all')
  const shown = data.contacts.filter(c => (filter === 'all' || c.subscription === filter) && `${c.name} ${c.email} ${c.organization} ${c.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))
  function exportContacts() {
    const rows = [['Name', 'Email', 'Organization', 'Subscription', 'Tags'], ...shown.map(c => [c.name, c.email, c.organization, c.subscription, c.tags.join('; ')])]
    const quote = (s: string) => `"${(/^[=+@\-\t\r]/.test(s) ? "'" + s : s).replaceAll('"', '""')}"`
    const blob = new Blob([rows.map(row => row.map(quote).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'signalgent-contacts.csv'; a.click(); URL.revokeObjectURL(url)
  }
  return <><Header title="People, not just addresses." description="A shared home for your contacts, context, and subscriptions."><button className="sg-button" onClick={exportContacts} disabled={!shown.length}><Download size={16} />Export</button><button className="sg-button sg-primary" onClick={() => setEditor({ kind: 'contact' })}><Plus size={16} />Add contact</button></Header><div className="sg-contact-stats"><span><strong>{data.contacts.length}</strong> contacts</span><span><strong>{data.contacts.filter(c => c.subscription === 'subscribed').length}</strong> subscribers</span><Link href="/outreach/contacts">Manage outreach prospects <ArrowUpRight size={14} /></Link></div><div className="sg-toolbar"><label className="sg-search-field"><Search size={16} /><input aria-label="Search contacts" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search names, companies, or tags…" /></label><select aria-label="Filter subscription" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All contacts</option><option value="subscribed">Subscribers</option><option value="not_subscribed">Not subscribed</option><option value="unsubscribed">Unsubscribed</option></select></div><div className="sg-table-wrap"><table className="sg-table"><thead><tr><th>Name</th><th>Organization</th><th>Tags</th><th>Email subscription</th><th><span className="sr-only">Edit</span></th></tr></thead><tbody>{shown.map(c => <tr key={c.id}><td><button className="sg-contact-name" onClick={() => setEditor({ kind: 'contact', item: c })}><span className="sg-person-avatar">{c.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</span><span><strong>{c.name}</strong><small>{c.email}</small></span></button></td><td>{c.organization || '—'}</td><td><div className="sg-tags">{c.tags.map(t => <span key={t}>{t}</span>)}</div></td><td><Status status={c.subscription} /></td><td><button className="sg-icon-button" aria-label={`Edit ${c.name}`} onClick={() => setEditor({ kind: 'contact', item: c })}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table>{!shown.length && <Empty title="Make your first connection" detail="Add contacts with notes and tags. Outreach prospects stay in your existing pipeline until you explicitly add them here." action={<button className="sg-button" onClick={() => setEditor({ kind: 'contact' })}>Add contact</button>} />}</div></>
}
function Calendar() {
  const { data, setEditor } = usePlatform()
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1))
  const [channel, setChannel] = useState('all')
  const [view, setView] = useState<'month' | 'list'>('month')
  const first = new Date(month); const mondayOffset = (first.getDay() + 6) % 7; first.setDate(first.getDate() - mondayOffset)
  const days = Array.from({ length: 42 }, (_, i) => new Date(first.getFullYear(), first.getMonth(), first.getDate() + i))
  const items = data.content.filter(c => c.planned_at && c.status !== 'archived' && (channel === 'all' || c.channels.includes(channel as Channel)))
  const monthly = items.filter(c => new Date(c.planned_at!).getMonth() === month.getMonth() && new Date(c.planned_at!).getFullYear() === month.getFullYear()).sort((a, b) => a.planned_at!.localeCompare(b.planned_at!))
  return <><Header title="A little structure. More possibility." description="See your email and social plans together, in your local time zone."><button className="sg-button sg-primary" onClick={() => setEditor({ kind: 'content' })}><Plus size={16} />Plan content</button></Header><div className="sg-calendar-toolbar"><div className="sg-row"><h2>{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h2><button className="sg-icon-button" aria-label="Previous month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft size={18} /></button><button className="sg-icon-button" aria-label="Next month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight size={18} /></button><button className="sg-button sg-compact" onClick={() => setMonth(new Date(new Date().getFullYear(), new Date().getMonth(), 1))}>Today</button></div><div className="sg-row"><select value={channel} aria-label="Calendar channel" onChange={e => setChannel(e.target.value)}><option value="all">All channels</option>{Object.entries(CHANNELS).map(([id, c]) => <option key={id} value={id}>{c.label}</option>)}</select><div className="sg-segmented"><button className={view === 'month' ? 'active' : ''} onClick={() => setView('month')}>Month</button><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}>List</button></div></div></div>
    {view === 'month' ? <div className="sg-calendar-scroll"><div className="sg-calendar-grid">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(d => <div className="sg-weekday" key={d}>{d}</div>)}{days.map(day => { const content = items.filter(c => new Date(c.planned_at!).toDateString() === day.toDateString()); const today = day.toDateString() === new Date().toDateString(); return <div key={day.toISOString()} className={`sg-calendar-day ${day.getMonth() !== month.getMonth() ? 'outside' : ''}`}><button className={`sg-day-number ${today ? 'is-today' : ''}`} aria-label={`Plan content for ${day.toLocaleDateString()}`} onClick={() => { const date = new Date(day); date.setHours(10); setEditor({ kind: 'content', date: date.toISOString() }) }}>{day.getDate()}</button>{content.map(item => <button key={item.id} className="sg-calendar-item" onClick={() => setEditor({ kind: 'content', item })} style={{ borderLeftColor: CHANNELS[item.channels[0]].color }}><span>{new Date(item.planned_at!).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</span><strong>{item.title}</strong><ChannelBadges channels={item.channels} /></button>)}</div> })}</div></div> : <section className="sg-panel">{monthly.map(item => <button key={item.id} className="sg-planned-row" onClick={() => setEditor({ kind: 'content', item })}><DateLabel value={item.planned_at} /><div className="sg-grow"><strong>{item.title}</strong><small>{item.channels.map(c => CHANNELS[c].label).join(', ')}</small></div><Status status={item.status} /></button>)}{!monthly.length && <Empty title="An open month ahead" detail="Add a date to a draft to see it here." />}</section>}
    <p className="sg-footer-note"><Clock3 size={14} />This calendar shows content plans, not confirmed deliveries. <Link href="/outreach/schedule">View the live outreach queue</Link></p></>
}
function Reports() {
  const { data } = usePlatform()
  const total = data.outreach.sent + data.outreach.queued + data.outreach.failed
  return <><Header title="Know what’s moving forward." description="Real workspace activity, with clear boundaries around what’s measured." /><div className="sg-stat-strip">{[{ name: 'Outreach sends', count: data.outreach.sent, detail: 'Provider sends recorded, all time' }, { name: 'Queued', count: data.outreach.queued, detail: 'Waiting in the outreach queue' }, { name: 'Failed sends', count: data.outreach.failed, detail: 'Review before retrying' }, { name: 'Subscribers', count: data.contacts.filter(c => c.subscription === 'subscribed').length, detail: 'Contacts with an opt-in record' }].map(s => <div className="sg-stat" key={s.name}><span>{s.name}</span><strong>{s.count.toLocaleString()}</strong><small>{s.detail}</small></div>)}</div><div className="sg-bottom-grid"><section className="sg-panel"><div className="sg-section-title"><div><h2>Outreach delivery states</h2><p>Recorded sends are not proof of inbox delivery.</p></div></div>{[{ name: 'Sent', count: data.outreach.sent, color: '#35785f' }, { name: 'Queued', count: data.outreach.queued, color: '#3461db' }, { name: 'Failed', count: data.outreach.failed, color: '#b9574c' }].map(s => <div className="sg-report-bar" key={s.name}><div><span>{s.name}</span><strong>{s.count}</strong></div><div className="sg-bar-track"><span style={{ width: `${total ? s.count / total * 100 : 0}%`, background: s.color }} /></div></div>)}</section><section className="sg-panel"><div className="sg-section-title"><div><h2>Content by channel</h2><p>A post with multiple channels counts in each.</p></div></div>{Object.entries(CHANNELS).map(([id, c]) => <div className="sg-channel-report" key={id}><span className="sg-channel-badge" style={{ background: c.color }}>{c.short}</span><span>{c.label}</span><strong>{data.content.filter(x => x.status !== 'archived' && x.channels.includes(id as Channel)).length}</strong><small>planned or drafted</small></div>)}</section></div><div className="sg-callout sg-report-callout"><ChartIcon /><div><h3>Engagement and conversion reporting comes next</h3><p>Reach, clicks, social replies, and attributed revenue will appear when publishing and analytics integrations are available. No estimated performance is displayed as real activity.</p></div></div></>
}
function ChartIcon() { return <PanelsTopLeft size={24} /> }
function Connections() {
  const { data, preview, companyId, notify } = usePlatform()
  const providers = [
    { id: 'gmail', name: 'Gmail', short: '@', color: '#3461db', description: 'Read, search, compose, and reply. Connect more than one mailbox.', capability: 'Mailbox operations', path: '/api/integrations/gmail/connect' },
    { id: 'outlook', name: 'Outlook', short: 'O', color: '#1267b2', description: 'Microsoft email support is planned for a future release.', capability: 'Mailbox integration pending', path: '' },
    { id: 'linkedin', name: 'LinkedIn', short: 'in', color: '#0a66c2', description: 'Connect your identity. Publishing needs additional approved access.', capability: 'Identity connection', path: '/api/integrations/linkedin/connect' },
    { id: 'instagram', name: 'Instagram', short: 'ig', color: '#b3437e', description: 'Plan your Instagram content now. Publishing and inbox access are not enabled.', capability: 'Publishing integration pending', path: '' },
    { id: 'facebook', name: 'Facebook', short: 'f', color: '#1877f2', description: 'Draft Facebook content alongside the rest of your channels.', capability: 'Publishing integration pending', path: '' },
    { id: 'pinterest', name: 'Pinterest', short: 'p', color: '#b82939', description: 'Connect Pinterest for its existing account and analytics integration.', capability: 'Account and analytics connection', path: '/api/integrations/pinterest/connect' },
  ]
  return <><Header title="Your channels. One home." description="Connect your accounts and see exactly what each connection supports." /><div className="sg-connections-grid">{providers.map(provider => { const accounts = data.accounts.filter(a => a.service === provider.id); return <section className="sg-connection-card" key={provider.id}><div className="sg-row sg-between"><span className="sg-provider-logo" style={{ background: provider.color }}>{provider.short}</span><span className="sg-capability">{provider.capability}</span></div><h2>{provider.name}</h2><p>{provider.description}</p><div className="sg-account-list">{accounts.map(a => <div key={a.id}><span className={`sg-connection-dot ${a.status === 'connected' ? 'connected' : ''}`} /><span>{a.label}</span><small>{a.status}</small></div>)}</div>{provider.path ? preview ? <button className="sg-button" onClick={() => notify('Connections are disabled in the sample workspace. Sign in to connect your accounts.')}><Plus size={15} />Connect account</button> : <a className={`sg-button ${!companyId ? 'sg-disabled-link' : ''}`} href={companyId ? `${provider.path}?companyId=${encodeURIComponent(companyId)}` : undefined}><Plus size={15} />{accounts.length ? 'Connect another account' : 'Connect account'}</a> : <span className="sg-coming-soon">Not available yet</span>}</section> })}</div><p className="sg-footer-note"><Plug size={14} />A connected identity does not grant publishing or messaging access. <Link href="/settings/connections">Manage existing integrations</Link></p></>
}
