export const MODES = {
  dashboard: {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    accent: '#8B7FF0',
    accentText: '#B8B0F8',
    cardBorder: '#1e1b3a',
    cardBg: '#120f22',
    mutedText: '#2e2850',
    subtleText: '#1a163a',
  },
  marketing: {
    id: 'marketing',
    label: 'Marketing',
    href: '/marketing',
    accent: '#D85A30',
    accentText: '#F0997B',
    cardBorder: '#272727',
    cardBg: '#1a1a1a',
    mutedText: '#5a3020',
    subtleText: '#3a1a08',
  },
  communications: {
    id: 'communications',
    label: 'Communications',
    href: '/communications',
    accent: '#1D9E75',
    accentText: '#5DCAA5',
    cardBorder: '#272727',
    cardBg: '#1a1a1a',
    mutedText: '#2a5040',
    subtleText: '#0d2218',
  },
  finance: {
    id: 'finance',
    label: 'Finance',
    href: '/finance',
    accent: '#BA7517',
    accentText: '#EF9F27',
    cardBorder: '#272727',
    cardBg: '#1a1a1a',
    mutedText: '#4a3000',
    subtleText: '#3a2a00',
  },
  commerce: {
    id: 'commerce',
    label: 'Commerce',
    href: '/commerce',
    accent: '#378ADD',
    accentText: '#85B7EB',
    cardBorder: '#272727',
    cardBg: '#1a1a1a',
    mutedText: '#0e2a50',
    subtleText: '#0a1e38',
  },
  analytics: {
    id: 'analytics',
    label: 'Analytics',
    href: '/analytics',
    accent: '#639922',
    accentText: '#97C459',
    cardBorder: '#272727',
    cardBg: '#1a1a1a',
    mutedText: '#1a3a00',
    subtleText: '#173404',
  },
} as const

export type ModeId = keyof typeof MODES
export type ModeConfig = (typeof MODES)[ModeId]
