export const MODES = {
  outreach: {
    id: 'outreach',
    label: 'Outreach',
    href: '/outreach',
    accent: '#c04b24',
    accentText: '#c04b24',
    cardBorder: '#e4e3df',
    cardBg: '#ffffff',
    mutedText: '#5a3020',
    subtleText: '#3a1a08',
  },
  dashboard: {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    accent: '#6a5aec',
    accentText: '#6a5aec',
    cardBorder: '#e4e3df',
    cardBg: '#ffffff',
    mutedText: '#2e2850',
    subtleText: '#1a163a',
  },
  marketing: {
    id: 'marketing',
    label: 'Marketing',
    href: '/marketing',
    accent: '#c04b24',
    accentText: '#c04b24',
    cardBorder: '#e4e3df',
    cardBg: '#ffffff',
    mutedText: '#5a3020',
    subtleText: '#3a1a08',
  },
  communications: {
    id: 'communications',
    label: 'Communications',
    href: '/communications',
    accent: '#17805f',
    accentText: '#17805f',
    cardBorder: '#e4e3df',
    cardBg: '#ffffff',
    mutedText: '#2a5040',
    subtleText: '#0d2218',
  },
  finance: {
    id: 'finance',
    label: 'Finance',
    href: '/finance',
    accent: '#9f6414',
    accentText: '#9f6414',
    cardBorder: '#e4e3df',
    cardBg: '#ffffff',
    mutedText: '#4a3000',
    subtleText: '#3a2a00',
  },
  commerce: {
    id: 'commerce',
    label: 'Commerce',
    href: '/commerce',
    accent: '#2173c5',
    accentText: '#2173c5',
    cardBorder: '#e4e3df',
    cardBg: '#ffffff',
    mutedText: '#0e2a50',
    subtleText: '#0a1e38',
  },
  analytics: {
    id: 'analytics',
    label: 'Analytics',
    href: '/analytics',
    accent: '#507c1c',
    accentText: '#507c1c',
    cardBorder: '#e4e3df',
    cardBg: '#ffffff',
    mutedText: '#1a3a00',
    subtleText: '#173404',
  },
} as const

export type ModeId = keyof typeof MODES
export type ModeConfig = (typeof MODES)[ModeId]
